const mainButton = document.getElementById("main-button");
const housesButton = document.getElementById("houses");
const hogwartsButton = document.getElementById("hogwarts");
const gamesButton = document.getElementById("games");
const bodySection = document.getElementById("page-body");


mainButton.onclick = function() {
    bodySection.innerHTML = "<div class=\"info-container\"><h1>Welcome!</h1><p>Welcome to Hogwarts School of Witchcraft and Wizardry!<br>Here you will learn about spells, potions, fantastic beasts, and so much more!<br>Scroll down to find more!</p><hr></div><div class=\"info-container\"><h2>The School</h2>	<div class=\"content\"><img src=\"./Images/hogwarts.jpeg\" alt=\"Hogwarts Castle\"><p>Hogwarts School of Witchcraft and Wizardry was founded around the 9th and 10th Centuries, by the 4 greatest Wizards of that time, Godric Griffindor, Helga Hufflepuff, Rowena Ravenclaw and Salazar Slitherin.<br>Established in the Scottish Highlands to educate young wizards and witches, as well to protect them from muggle persecution.</p></div><hr></div><div class=\"info-container\"><h2>The Houses</h2><div class=\"content\"><p>In the Sorting Ceremony you will be sorted into one of the 4 Hogwarts` Houses. There is Ravenclaw, for the ones with a ready mind, Griffindor, for the brave and courageous, Hufflepuff, for the kind, and Slitherin, for the sneaky sneaky.<br>While at Hogwarts, your House is your family. You will share most of your time here together, wether in the classroom or in your House`s Common Room.</p><img src=\"./Images/houses.png\" alt=\"Hogwarts Houses\"></div><hr></div><div class=\"info-container\"><h2>The Students</h2><div class=\"content\"><img src=\"./Images/students.jpeg\" alt=\"Hogwarts Students\"><p>In Hogwarts you will find many minds that seem to understand your magical way of seeing the world!<br>In your House, as well in others, you will make friends that will always be there for you during your magical journey, and throughout life!</p></div><hr></div>";
}

housesButton.onclick = function () {
    bodySection.innerHTML = "<div class=\"info-container\"><h1>The Houses</h1><p>Hogwarts is divided into four houses, each bearing the last name of its founder: Godric Gryffindor, Salazar Slytherin, Rowena Ravenclaw and Helga Hufflepuff. Throughout the school year, the houses compete for the House Cup, gaining and losing points based on actions such as performance in class and rule violations. The house with the highest end-of-year total wins and has its colours displayed in the Great Hall for the following school year.<br>Scroll down to find out more!</p><hr></div><div class=\"info-container\"><h2>Gryffindor</h2><div class=\"content\"><img src=\"./Images/gryffindor.png\" alt=\"Gryffindor\"><p>Gryffindor values courage, bravery, nerve, and chivalry. Gryffindor's mascot is the lion, and its colours are scarlet red and gold. The Gryffindor common room is in one of the castle's highest towers, and its entrance is on the seventh floor in the east wing of the castle and is guarded by a painting of The Fat Lady.</p></div><hr></div><div class=\"info-container\"><h2>Slytherin</h2><div class=\"content\"><p>Slytherin values ambition, cunning, leadership, and resourcefulness. The house mascot of Slytherin is the serpent, and the house colours are green and silver. The Slytherin dormitories and common room are reached by speaking a password to a patch of bare stone wall in the dungeons, which causes a hidden door to open. The Sorting Hat claims that blood purity is a factor in selecting Slytherins.</p><img src=\"./Images/slytherin.png\" alt=\"Slytherin\"></div><hr></div><div class=\"info-container\"><h2>Ravenclaw</h2><div class=\"content\"><img src=\"./Images/ravenclaw.png\" alt=\"Ravenclaw\"><p>Ravenclaw values intelligence, learning, wisdom and wit. The house mascot is an eagle and the house colours are blue and bronze. The dormitories are in Ravenclaw Tower, on the west side of Hogwarts. The common room is round and filled with blue hangings and armchairs, has a domed ceiling painted with stars and features a replica statue of Rowena wearing her diadem. A logical riddle must be solved to gain entry, whereas the Gryffindor and Slytherin common rooms only require a password.</p></div><hr></div><div class=\"info-container\"><h2>Hufflepuff</h2><div class=\"content\"><p>Hufflepuff values hard work, patience, justice, and loyalty. The house mascot is the badger, and canary yellow and black are its colours. The entrance to the Hufflepuff dormitories and common room entrance is concealed in a pile of large barrels in an alcove in the corridor that holds the kitchen. To enter, one must tap the barrel two from the bottom in the middle of the second row in the rhythm of \"Helga Hufflepuff\".</p><img src=\"./Images/hufflepuff.png\" alt=\"Hufflepuff\"></div><hr></div>";
}

hogwartsButton.onclick = function () {
    bodySection.innerHTML = "<div class=\"info-container\"><h1>The School</h1><p>Founded around the 9th century and 10th century by Godric Gryffindor, Rowena Ravenclaw, Helga Hufflepuff and Salazar Slytherin, Hogwarts was established in the Highlands of Scotland to educate young wizards and witches as well as to keep students safe from muggle persecution. Theory has it that Rowena Ravenclaw came up with the name of Hogwarts after dreaming of a warty hog that led her to a cliff by a lake. Since then, Hogwarts educated most wizarding children with residence in Great Britain and Ireland, keeping its location hidden from other wizarding schools and muggles.</p><p>About three hundred years after the school was founded, the Triwizard Tournament was established as an interscholastic competition among the three most prestigious magical schools in Europe: Hogwarts, Beauxbatons, and Durmstrang. The tournament continued for six centuries before being discontinued. An attempt was made in the 1994-1995 school year to revive the tournament, but the consequential death of Cedric Diggory resulted in its permanent discontinuation.</p><p>Hogwarts is a coeducational, secondary boarding school, taking children from ages eleven to seventeen. Education at Hogwarts is not compulsory, with some students being home schooled as stated in the seventh book. Rowling initially said there are about one thousand students at Hogwarts. She later suggested around six hundred, while acknowledging that this number was still inconsistent with the small number of people in Harry's year. She further explained that this had resulted from her creating only forty characters for Harry's year.</p></div>";
}

gamesButton.onclick = function () {
    bodySection.innerHTML = "<div class=\"info-container\"><h1>Wizarding Games</h1><p>Magical games to exercise the magic within!<br>Scroll Down!</p></div>";
}